### PR TITLE
Database setup v2

### PR DESCRIPTION
**Pull request by ioshir4350**
Models created & Atlas connected. I also did my socket database operations.

### CODE REVIEW

**Comment by ioshir4350** [comment]
I am going to need help resolving the conflicts.

**Review by nedjulius — COMMENTED** [review]
Added `db` file that contains database connection information and fixed merge conflicts. @ioshir4350 did you try if this works? Also, next time please open up PRs for different features as we spoke before.

**Review by nedjulius — COMMENTED** [review]
And don't forget to slide your cards in the project

**Comment by ioshir4350** [comment]
@nedjulius I have not seen if the separate db file works. But if it works on your side, then we should be good right?

**Pull request merged**
